name: Publish to Nuget

on:
  push:
    branches: [ main ]
    paths:
      - 'StreamRegex.Extensions/**'
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0 # avoid shallow clone so nbgv can do its work.
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x
    - name: Nerdbank.GitVersioning
      # You may pin to the exact commit or the version.
      # uses: dotnet/nbgv@49d4f35f34d895d282b99855b2e0034f8f608ba5
      uses: dotnet/nbgv@v0.4.0
      with:
        setAllVars: true
      
    - name: Restore dependencies
      run: dotnet restore
    - name: Test Before Publish
      run: dotnet test --verbosity normal -f net7.0
    - name: Build
      run: dotnet pack --no-restore StreamRegex.Extensions -o NuPkgs
    - name: Setup NuGet.exe for use with actions
      uses: NuGet/setup-nuget@v1.0.5
      with:
        nuget-api-key: ${{secrets.NUGET_API_KEY}}
    - name: Nuget Publish
      run: nuget push NuPkgs/*.*nupkg -Source https://api.nuget.org/v3/index.json