name: Publish to Nuget

on:
  push:
    branches: [ main ]
    paths:
      - 'StreamRegex.Extensions/**'
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0 # avoid shallow clone so nbgv can do its work.
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          8.0.x
          9.0.x
          10.0.x
        include-prerelease: true
    - name: Nerdbank.GitVersioning
      uses: dotnet/nbgv@v0.4.0
      with:
        setAllVars: true
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: Build
      run: dotnet pack --no-restore StreamRegex.Extensions -o NuPkgs
    - name: Nuget Publish
      run: dotnet nuget push NuPkgs/*.nupkg --api-key ${{secrets.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json
