name: Run Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0 # avoid shallow clone so nbgv can do its work.
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x
        include-prerelease: true
    - name: Nerdbank.GitVersioning
      # You may pin to the exact commit or the version.
      # uses: dotnet/nbgv@49d4f35f34d895d282b99855b2e0034f8f608ba5
      uses: dotnet/nbgv@v0.4.0
      with:
        setAllVars: true
      
    - name: Restore dependencies
      run: dotnet restore
    - name: Test
      run: dotnet test --verbosity normal -f net6.0
